# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure access gateway N-Port settings
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    n_port_settings:
      reliability_counter: 25

  tasks:
    - name: Ag N-Port settings
      brocade_access_gateway_n_port_settings:
        credential: "{{ credential }}"
        vfid: -1
        n_port_settings: "{{ n_port_settings }}"
