---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    action_inputs:
      remote_user_name: user_name
      remote_host_ip: host_ip
      remote_user_password: user_password_in_clear_text
      remote_directory: directory_of_cert
      protocol: scp
      certificate_entity: cert
      certificate_type: https
      certificate_name: cert_name
      operation: import

  tasks:

  - name: Cert installation. Existing cert is not compared. This task will always change.
    brocade_security_security_certificate_action:
      credential: "{{credential}}"
      vfid: -1
      action_inputs: "{{action_inputs}}"
