# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Gather logical switch facts
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Gather facts for brocade_fibrechannel_switch_fibrechannel_switch
      brocade_list_obj_facts:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_fibrechannel_logical_switch"
        list_name: "fibrechannel_logical_switch"

    - name: Print ansible_facts gathered
      ansible.builtin.debug:
        var: ansible_facts
