# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Gather relay server facts
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Relay server
      brocade_singleton_obj_facts:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade-maps"
        obj_name: "maps-config"

    - name: Print accumulative ansible_facts gathered
      ansible.builtin.debug:
        var: ansible_facts
