# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Find name server by port type
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    port_type_to_search: "n-port"

  tasks:
    - name: Gather facts
      brocade_list_obj_facts:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade-name-server"
        list_name: "fibrechannel-name-server"
        attributes:
          port_type: "{{ port_type_to_search }}"

    - name: Print ansible_facts gathered
      ansible.builtin.debug:
        var: ansible_facts
