namespace: brocade
name: fos
version: 2.1.0
readme: README.rst
authors:
  - Brocade Automation Team <Automation.BSN@broadcom.com>
description: Collection of modules to manage Brocade FOS Fibre Channel (FC) switches
license:
  - GPL-3.0-or-later
  - BSD-2-Clause
# license_file: COPYING
tags:
  - brocade
  - fos
  - storage
  - san
  - fibre_channel
  - fc
dependencies: {}
repository: https://github.com/brocade/ansible
documentation: https://galaxy.ansible.com/ui/repo/published/brocade/fos/docs/
homepage: https://github.com/brocade/ansible
issues: https://github.com/brocade/ansible/issues
