# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure IPS
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars_files: ipsdb.yml

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Configure all non-default logical switch
      brocade_fibrechannel_logical_switch_fibrechannel_logical_switch:
        credential: "{{ credential }}"
        vfid: -1
        all_entries: false
        logical_switches: "{{ logicalswitches }}"

    - name: Configure vrf
      brocade_operation:
        credential: "{{ credential }}"
        module_name: vrf
        vfid: "{{ fabric_id }}"
        entries: "{{ vrfs }}"

    - name: Configure vlan
      brocade_operation:
        credential: "{{ credential }}"
        module_name: vlan
        vfid: "{{ fabric_id }}"
        entries: "{{ vlans }}"

    - name: Configure interface
      brocade_operation:
        credential: "{{ credential }}"
        module_name: interface
        vfid: "{{ fabric_id }}"
        entries: "{{ interfaces }}"

    - name: Configure staticArp
      brocade_operation:
        credential: "{{ credential }}"
        module_name: staticArp
        vfid: "{{ fabric_id }}"
        entries: "{{ staticarps }}"

    - name: Configure staticRoute
      brocade_operation:
        credential: "{{ credential }}"
        module_name: staticRoute
        vfid: "{{ fabric_id }}"
        entries: "{{ staticroutes }}"

    - name: Configure lag
      brocade_operation:
        credential: "{{ credential }}"
        module_name: lag
        vfid: "{{ fabric_id }}"
        entries: "{{ lags }}"

    - name: Configure trafclass
      brocade_operation:
        credential: "{{ credential }}"
        module_name: configuration
        vfid: "{{ fabric_id }}"
        entries: "{{ trafclasses }}"
