---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"

  tasks:

  - name: create my policy
    brocade_maps_maps_policy:
      credential: "{{credential}}"
      vfid: -1
      maps_policies:
        - name: my_policy
          is_active_policy: False
          rule_list:
            rule:
              - my_rule1
              - my_rule2
