# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure relay server
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    maps_config:
      relay_ip_address: "198.51.100.2"
      domain_name: "domain2.example.com"
      sender_address: "sender@domain2.example.com"
      recipient_address_list:
        recipient_address:
          - "receiver@domain2.example.com"

  tasks:
    - name: Configure relay server
      brocade_maps_maps_config:
        credential: "{{ credential }}"
        vfid: -1
        maps_config: "{{ maps_config }}"
