---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    action_inputs:
      template_name: default_generic
      action: apply

  tasks:

  - name: apply template. warning - this task will always change.
    brocade_security_sec_crypto_cfg_template_action:
      credential: "{{credential}}"
      vfid: -1
      action_inputs: "{{action_inputs}}"
