---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    action_inputs:
      remote_user_name: username
      remote_host_ip: "xx.xx.xx.xx"
      remote_user_password: password
      remote_directory: /home/username/.ssh
      user_name: admin
      public_key_name: id_rsa.pub
      action: import

  tasks:

  - name: import public key. Existing public key is not compared. The task will always change.
    brocade_security_sshutil_public_key_action:
      credential: "{{credential}}"
      vfid: -1
      action_inputs: "{{action_inputs}}"
