---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    obj_list:
      brocade_access_gateway:
        - policy
        - n_port_settings
      brocade_chassis:
        - chassis
        - ha_status
      brocade_fibrechannel_configuration:
        - switch_configuration
        - f_port_login_settings
        - port_configuration
        - zone_configuration
        - fabric
      brocade_logging:
        - audit
        - log_setting
      brocade_maps:
        - switch_status_policy_report
        - system_resources
        - maps_config
        - dashboard_misc
      brocade_security:
        - password_cfg
        - auth_spec
        - sec_crypto_cfg
        - sshutil
      brocade_snmp:
        - system
      brocade_time:
        - time_zone
        - clock_server
    list_list:
      brocade_access_gateway:
        - port_group
        - n_port_map
        - f_port_list
        - device_list
      brocade_extension_ip_route:
        - extension_ip_route
      brocade_extension_ipsec_policy:
        - extension_ipsec_policy
      brocade_extension_tunnel:
        - extension_tunnel
        - extension_tunnel_statistics
        - extension_circuit_statistics
      brocade_fabric:
        - fabric_switch
      brocade_fdmi:
        - hba
        - port
      brocade_fibrechannel_logical_switch:
        - fibrechannel_logical_switch
      brocade_fibrechannel_switch:
        - fibrechannel_switch
      brocade_fibrechannel_trunk:
        - trunk
        - performance
        - trunk_area
      brocade_fru:
        - blade
        - fan
        - power_supply
      brocade_interface:
        - fibrechannel
        - fibrechannel_statistics
        - extension_ip_interface
        - gigabitethernet
        - gigabitethernet_statistics
      brocade_license:
        - license
      brocade_logging:
        - syslog_server
        - raslog
        - raslog_module
        - log_quiet_control
      brocade_maps:
        - paused_cfg
        - group
        - dashboard_rule
        - rule
        - monitoring_system_matrix
      brocade_media:
        - media_rdp
      brocade_name_server:
        - fibrechannel_name_server
      brocade_security:
        - ipfilter_policy
        - ipfilter_rule
        - user_specific_password_cfg
        - user_config
        - radius_server
        - tacacs_server
        - ldap_server
        - ldap_role_map
        - sec_crypto_cfg_template
        - sshutil_key
        - sshutil_public_key
        - security_certificate
      brocade_snmp:
        - mib_capability
        - trap_capability
        - v1_account
        - v1_trap
        - v3_account
        - v3_trap


  tasks:

  - name: gather facts
    brocade_facts:
      credential: "{{credential}}"
      vfid: -1
      gather_subset:
        - brocade_zoning

  - name: gather non-zoning facts - non-list object
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "{{ item.0.key }}"
      obj_name: "{{ item.1 }}"
    loop: "{{ obj_list | dict2items | subelements('value') }}"

  - name: gather non-zoning facts - list object
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "{{ item.0.key }}"
      list_name: "{{ item.1 }}"
    loop: "{{ list_list | dict2items | subelements('value') }}"

  - name: print ansible_facts gathered
    debug:
      var: ansible_facts
