# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Apply template switch configuration changes
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Disable switch
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_fibrechannel_switch"
        list_name: "fibrechannel_switch"
        entries:
          - enabled_state: false

    - name: Change all switch configuration
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_fibrechannel_switch"
        list_name: "fibrechannel_switch"
        entries:
          - user_friendly_name: "new_switch_name"
            fabric_user_friendly_name: "new_fabric_name"
            domain_id: 2
            banner: "MORE AUTHORIZED USERS ONLY"
            dynamic_load_sharing: "two-hop-lossless-dls"
            domain_name: "google.com"
            dns_servers:
              dns_server:
                - "9.8.8.8"

    - name: Change all switch configuration
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_fibrechannel_switch"
        list_name: "fibrechannel_switch"
        entries:
          - user_friendly_name: "new_switch_name"
            fabric_user_friendly_name: "new_fabric_name"
            domain_id: 2
            banner: "MORE AUTHORIZED USERS ONLY"
            dynamic_load_sharing: "two-hop-lossless-dls"
            domain_name: "example.com"
            dns_servers:
              dns_server:
                - "203.0.113.30"

  # - debug: var=result

    - name: >
        Change all port configuration. if running on a platform where credit
        recovery is supported, the line can be uncommented to update the mode.
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_fibrechannel_configuration"
        obj_name: "port_configuration"
        attributes:
          dynamic_portname_format: "T.A.R"
          portname_mode: "off"
              # credit_recovery_mode: "off"

    - name: Enable switch
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_fibrechannel_switch"
        list_name: "fibrechannel_switch"
        entries:
          - enabled_state: true

    - name: Change all chassis configuration
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_chassis"
        obj_name: "chassis"
        attributes:
          chassis_user_friendly_name: "new_chassis_name"
        # shell_timeout is the REST name for telnet_timeout
          telnet_timeout: 60

    - name: Configure ports
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_interface"
        list_name: "fibrechannel"
        all_entries: false
        entries:
          - name: "0/0"
            enabled_state: true
            npiv_pp_limit: 126
          - name: "0/1"
            persistent_disable: false

    - name: Pause to make sure ports are configured
      ansible.builtin.pause:
        seconds: 15

    - name: Change all zoning configuration
      brocade_zoning_default_zone:
        credential: "{{ credential }}"
        vfid: -1
        default_zone_access: noaccess

    - name: Change all clock server configuration
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_time"
        obj_name: "clock_server"
        attributes:
          ntp_server_address:
            server_address:
              - "203.0.113.20"
              - "203.0.113.21"

    - name: Change all time zone configuration
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_time"
        obj_name: "time_zone"
        attributes:
          name: "America/Los_Angeles"

    - name: Change all audit configuration
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_logging"
        obj_name: "audit"
        attributes:
          audit_enabled: false
          filter_class_list:
            filter_class:
              - "zone"
              - "security"
              - "configuration"
              - "firmware"
              - "fabric"
              - "ls"
          severity_level: "warning"

    - name: Change all syslog configuration
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_logging"
        list_name: "syslog_server"
        entries:
          - port: 514
            secure_mode: false
            server: "203.0.113.10"

    - name: Change all SNMP system configuration
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_snmp"
        obj_name: "system"
        attributes:
          audit_interval: 60
          contact: "more Field Support."
          description: "more DemoSwitch"
          encryption_enabled: true
          location: "Data Center 2"
          security_get_level_string: "authentication-and-privacy"
          security_set_level_string: "authentication-and-privacy"

    - name: SNMP v3 accounts - setup non-password attributes
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_snmp"
        list_name: "v3_account"
        all_entries: false
        entries:
          - index: 1
            authentication_protocol: "sha512"
            privacy_protocol: "aes128"
            user_name: "snmpadmin11"
          - index: 2
            authentication_protocol: "sha512"
            privacy_protocol: "aes128"
            user_name: "snmpadmin22"

    - name: SNMP v3 traps
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_snmp"
        list_name: "v3_trap"
        entries:
          - trap_index: 1
            host: "198.51.100.5"
            informs_enabled: false
            port_number: 1031
            trap_severity_level: "critical"
            usm_index: 1
          - trap_index: 2
            host: "198.51.100.6"
            informs_enabled: false
            port_number: 1032
            trap_severity_level: "warning"
            usm_index: 2
          - trap_index: 3
            host: "0.0.0.0"
            informs_enabled: false
            port_number: 162
            trap_severity_level: "none"
            usm_index: 3
          - trap_index: 4
            host: "0.0.0.0"
            informs_enabled: false
            port_number: 162
            trap_severity_level: "none"
            usm_index: 4
          - trap_index: 5
            host: "0.0.0.0"
            informs_enabled: false
            port_number: 162
            trap_severity_level: "none"
            usm_index: 5
          - trap_index: 6
            host: "0.0.0.0"
            informs_enabled: false
            port_number: 162
            trap_severity_level: "none"
            usm_index: 6

    - name: Disable inform after updating v3 traps
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_snmp"
        obj_name: "system"
        attributes:
          informs_enabled: false

    - name: Activate default ipv4 before deleting previously created custom policy
      brocade_security_ipfilter_policy:
        credential: "{{ credential }}"
        vfid: -1
        active_policy: "default_ipv4"

    - name: Delete custom policy
      brocade_security_ipfilter_policy:
        credential: "{{ credential }}"
        vfid: -1
        delete_policies:
          - name: "Ipv4_telnet_http"

    - name: >
        Leave admin along, enable root & user and delete myaccount and
        youraccount. For 9.0.0, maintanenance account was added.
      brocade_list_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_security"
        list_name: "user_config"
        entries:
        # - name: "maintenance"
        #   account_enabled: true
          - name: "User"
            account_enabled: true
          - name: "Admin"
            account_enabled: true
          - name: "Root"
            account_enabled: true

    - name: Configure relay server
      brocade_singleton_obj:
        credential: "{{ credential }}"
        vfid: -1
        module_name: "brocade_maps"
        obj_name: "maps_config"
        attributes:
          relay_ip_address: "198.51.100.2"
          domain_name: "domain2.example.com"
          sender_address: "sender@domain2.example.com"
          recipient_address_list:
            recipient_address:
              - "receiver@domain2.example.com"
