---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: zone_migration_app
  gather_facts: False

  vars:
    f_credential:
      fos_ip_addr: "{{f_fos_ip_addr}}"
      fos_user_name: "{{f_fos_user_name}}"
      fos_password: "{{f_fos_password}}"
      https: "{{f_fos_https}}"
    t_credential:
      fos_ip_addr: "{{t_fos_ip_addr}}"
      fos_user_name: "{{t_fos_user_name}}"
      fos_password: "{{t_fos_password}}"
      https: "{{t_fos_https}}"

  tasks:

  - name: gather facts
    brocade_facts:
      credential: "{{f_credential}}"
      vfid: -1
      gather_subset:
        - brocade_zoning_simple

  - name: print ansible_facts gathered
    debug:
      var: ansible_facts['brocade_zoning_simple']

  - name: Create aliases
    brocade_zoning_alias:
      credential: "{{t_credential}}"
      vfid: -1
      aliases: "{{ansible_facts['brocade_zoning_simple']['defined_configuration']['aliases']}}"

  - name: Create zones
    brocade_zoning_zone:
      credential: "{{t_credential}}"
      vfid: -1
      zones: "{{ansible_facts['brocade_zoning_simple']['defined_configuration']['zones']}}"

  - name: Create cfgs
    brocade_zoning_cfg:
      credential: "{{t_credential}}"
      vfid: -1
      cfgs: "{{ansible_facts['brocade_zoning_simple']['defined_configuration']['cfgs']}}"
      active_cfg: "{{ansible_facts['brocade_zoning_simple']['effective_configuration']['cfg_name']}}"

#  - name: Default zoning
#    brocade_zoning_default_zone:
#      credential: "{{credential}}"
#      vfid: -1
#      default_zone_access: allaccess
