---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    aliases:
      - name: Host1
        members:
          - aa:22:22:22:22:22:22:22
    zones:
      - name: Zone3
        members:
          - aa:55:55:55:55:55:55:55
        principal_members:
          - aa:aa:aa:aa:cc:cc:cc:CC
    cfgs:
      - name: cfg1
        members:
          - Zone2

  tasks:

  - name: after zoning_zone.yml, remove aa:11:11:11:11:11:11:11 from Host1 by specifying all members
    brocade_zoning_alias:
      credential: "{{credential}}"
      vfid: -1
      aliases: "{{aliases}}"

  - name: after zoning_zone.yml, remove aa:44:44:44:44:44:44:44/aa:aa:aa:aa:bb:bb:bb:bb from Zone3 by specifying all members
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      zones: "{{zones}}"

  - name: after zoning_zone.yml, remove Zone1 from cfg1 by specifying all members and leave it enabled
    brocade_zoning_cfg:
      credential: "{{credential}}"
      vfid: -1
      cfgs: "{{cfgs}}"
      active_cfg: cfg1
