# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Add and remove zones
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    aliases:
      - name: alias_host_1
        members:
          - aa:bb:cc:dd:ee:ff:11:24
    zones:
      - name: zone_3
        members:
          - aa:bb:cc:dd:ee:ff:11:24
        principal_members:
          - aa:bb:cc:dd:ee:ff:11:26
      - name: zone_4
        members:
          - aa:bb:cc:dd:ee:ff:11:23
        principal_members:
          - aa:bb:cc:dd:ee:ff:11:25
    cfgs:
      - name: cfg_1
        members:
          - zone_4

  tasks:
    - name: >
        After zoning_zone.yml, add cc:99:99:99:99:99:99:99 and remove
        aa:11:11:11:11:11:11:11/aa:22:22:22:22:22:22:22 from Host1 by
        specifying the final member list
      brocade_zoning_alias:
        credential: "{{ credential }}"
        vfid: -1
        aliases: "{{ aliases }}"

    - name: >
        After zoning_zone.yml, add aa:bb:cc:dd:ee:ff:11:24 and remove
        aa:bb:cc:dd:ee:ff:11:1a/aa:bb:cc:dd:ee:ff:11:1b from alias_host_1 by
        specifying the final member list
      brocade_zoning_alias:
        credential: "{{ credential }}"
        vfid: -1
        aliases: "{{ aliases }}"

    - name: >
        After zoning_zone.yml, add aa:bb:cc:dd:ee:ff:11:24/aa:bb:cc:dd:ee:ff:11:26
        and remove aa:bb:cc:dd:ee:ff:11:1c/aa:bb:cc:dd:ee:ff:11:1d/
        aa:bb:cc:dd:ee:ff:11:1e/aa:bb:cc:dd:ee:ff:11:1f from zone_3 by
        specifying the final member list. Also, create zone_4.
      brocade_zoning_zone:
        credential: "{{ credential }}"
        vfid: -1
        zones: "{{ zones }}"

    - name: After zoning_zone.yml, add zone_4 and remove zone_1/zone_2. And leave
        cfg_1 enabled
      brocade_zoning_cfg:
        credential: "{{ credential }}"
        vfid: -1
        cfgs: "{{ cfgs }}"
        active_cfg: cfg_1
