# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Disable access gateway mode
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Disable switch before disabling ag mode
      brocade_fibrechannel_switch:
        credential: "{{ credential }}"
        vfid: -1
        switch:
          enabled_state: false

    - name: Disable ag mode. switch will reboot afterward.
      brocade_fibrechannel_switch:
        credential: "{{ credential }}"
        vfid: -1
        switch:
          ag_mode: 1
