# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure access gateway policy
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    policy:
      auto_policy_enabled: false
      port_group_policy_enabled: true

  tasks:
    - name: Ag policy
      brocade_access_gateway_policy:
        credential: "{{ credential }}"
        vfid: -1
        policy: "{{ policy }}"
