---

# Copyright 2024 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False
  collections:
    - brocade.fos

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"
    configdownload:
      config_upload_download_option: "virtual-fabric"
      config_input_buffer: "copy config_output_buffer value of configupload here"


  tasks:

  - name: configdownload
    brocade_scalar_operation:
      credential: "{{credential}}"
      module_name: "configdownload"
      vfid: -1
      entries: "{{configdownload}}"
    register: result

  - name: print initial results gathered
    debug:
      var: result.operation_resp

  - name: pause for few minutes for switch reboot
    pause:
      minutes: 5

  - name: show status after reboot
    brocade_operation_show_status:
      credential: "{{credential}}"
      vfid: -1
      show_status:
        message_id: "{{result.operation_resp.show_status.message_id}}"
    register: status_result
    until: status_result.operation_resp is not defined or status_result.operation_resp.show_status.status == "done" or status_result.operation_resp.show_status.status == "delivered"
    retries: 100
    delay: 10

  - name: print show_status end result
    debug:
      var: status_result.operation_resp
