# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Gather security certificate facts
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Gather facts
      brocade_facts:
        credential: "{{ credential }}"
        vfid: -1
        gather_subset:
          - brocade_security_security_certificate

    - name: Print ansible_facts gathered
      ansible.builtin.debug:
        var: ansible_facts
