# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure MAPS rule
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  tasks:
    - name: Create my rules
      brocade_maps_rule:
        credential: "{{ credential }}"
        vfid: -1
        rules:
          - name: My_rule1
            actions:
              action:
                - "raslog"
            event_severity:
            group_name: "ALL_E_PORTS"
            is_rule_on_rule: false
            logical_operator: "g"
            monitoring_system: "C3TXTO"
            quiet_time: 0
            threshold_value: 1
            time_base: "Min"
          - name: My_rule2
            actions:
              action:
                - "raslog"
            event_severity:
            group_name: "ALL_E_PORTS"
            is_rule_on_rule: false
            logical_operator: "g"
            monitoring_system: "C3TXTO"
            quiet_time: 0
            threshold_value: 1
            time_base: "Min"
