# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure SNMP
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    snmp_system:
      audit_interval: 60
      contact: "more Field Support."
      description: "more DemoSwitch"
      encryption_enabled: true
      informs_enabled: true
      location: "Data Center 2"
      security_get_level_string: 'authentication-and-privacy'
      security_set_level_string: 'authentication-and-privacy'
    v3_accounts:
      - index: 1
        authentication_protocol: "sha512"
        manager_engine_id: "00:00:00:00:00:00:00:00:00"
        privacy_protocol: "aes128"
        user_name: "asc-test"
        user_group: "read-only"
        authentication_password: "user_password"
        privacy_password: "user_password"
      - index: 2
        authentication_protocol: "sha512"
        manager_engine_id: "00:00:00:00:00:00:00:00:00"
        privacy_protocol: "aes256"
        user_name: "snmpadmin2"
        user_group: "read-write"
        authentication_password: "password2"
        privacy_password: "password2"
    v3_traps:
      - trap_index: 1
        host: "198.51.100.2"
        informs_enabled: true
        port_number: 1011
        trap_severity_level: "warning"
        usm_index: 1
      - trap_index: 2
        host: "198.51.100.1"
        informs_enabled: false
        port_number: 1010
        trap_severity_level: "critical"
        usm_index: 2
      - trap_index: 3
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 3
      - trap_index: 4
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 4
      - trap_index: 5
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 5
      - trap_index: 6
        host: "0.0.0.0"
        informs_enabled: false
        port_number: 162
        trap_severity_level: "none"
        usm_index: 6
    v3_accounts_passwords_only:
      - index: 1
        authentication_password: "user_password"
        privacy_password: "user_password"
      - index: 2
        authentication_password: "password2"
        privacy_password: "user_password"

  tasks:
    - name: Change all snmp system configuration
      brocade_snmp_system:
        credential: "{{ credential }}"
        vfid: -1
        snmp_system: "{{ snmp_system }}"

    - name: Change all SNMP system configuration
      brocade_snmp_system:
        credential: "{{ credential }}"
        vfid: -1
        snmp_system: "{{ snmp_system }}"

    - name: SNMP v3 accounts - setup attributes
      brocade_snmp_v3_account:
        credential: "{{ credential }}"
        vfid: -1
        v3_accounts: "{{ v3_accounts }}"

    - name: SNMP v3 traps
      brocade_snmp_v3_trap:
        credential: "{{ credential }}"
        vfid: -1
        v3_traps: "{{ v3_traps }}"

    - name: SNMP v3 accounts - set passwords. warning - password cannot be read.
        this task will always change.
      brocade_snmp_v3_account:
        credential: "{{ credential }}"
        vfid: -1
        v3_accounts: "{{ v3_accounts_passwords_only }}"
