# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Import SSH public key
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    action_inputs:
      remote_user_name: user_name
      remote_host_ip: "198.51.100.254"
      remote_user_password: password
      remote_directory: /home/user_name/.ssh
      user_name: admin
      public_key_name: id_rsa.pub
      action: import

  tasks:
    - name: Import public key. Existing public key is not compared. The task will
        always change.
      brocade_security_sshutil_public_key_action:
        credential: "{{ credential }}"
        vfid: -1
        action_inputs: "{{ action_inputs }}"
