# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Delete SSH public key
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    delete_sshutil_public_key:
      - user_name: "user_name"

  tasks:
    - name: Delete public keys for admin
      brocade_security_sshutil_public_key:
        credential: "{{ credential }}"
        vfid: -1
        delete_sshutil_public_key: "{{ delete_sshutil_public_key }}"
