# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

# This playbook is an example of how to use zonedb.yml
# that contains exising defined zone database.
- name: Apply zone database from variables
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"

  vars_files:
    - zonedb.yml

  tasks:
    - name: Create aliases
      brocade_zoning_alias:
        credential: "{{ credential }}"
        vfid: -1
        aliases: "{{ aliases }}"
            # aliases_to_delete: "{{ aliases_to_delete }}"

    - name: Create zones
      brocade_zoning_zone:
        credential: "{{ credential }}"
        vfid: -1
        zones: "{{ zones }}"
            # zones_to_delete: "{{ zones_to_delete }}"

    - name: Create cfgs
      brocade_zoning_cfg:
        credential: "{{ credential }}"
        vfid: -1
        cfgs: "{{ cfgs }}"
        # cfgs_to_delete: "{{ cfgs_to_delete }}"
        active_cfg: newcfg2

    - name: Default zoning
      brocade_zoning_default_zone:
        credential: "{{ credential }}"
        vfid: -1
        default_zone_access: allaccess
