# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Remove zone members only
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    aliases:
      - name: alias_host_1
        members:
          - aa:bb:cc:dd:ee:ff:11:1a
    zones:
      - name: zone_3
        members:
          - aa:bb:cc:dd:ee:ff:11:1c
        principal_members:
          - aa:bb:cc:dd:ee:ff:11:1e
    cfgs:
      - name: cfg_1
        members:
          - zone_1

  tasks:
    - name: >
        After zoning_zone.yml, remove aa:11:11:11:11:11:11:11 from Host1 by
        specifying only those members being removed and setting
        members_remove_only to True
      brocade_zoning_alias:
        credential: "{{ credential }}"
        vfid: -1
        members_remove_only: true
        aliases: "{{ aliases }}"

    - name: >
        After zoning_zone.yml, remove aa:bb:cc:dd:ee:ff:11:1a from alias_host_1
        by
        specifying only those members being removed and setting
        members_remove_only to True
      brocade_zoning_alias:
        credential: "{{ credential }}"
        vfid: -1
        members_remove_only: true
        aliases: "{{ aliases }}"

    - name: >
        After zoning_zone.yml, remove aa:bb:cc:dd:ee:ff:11:1c/
        aa:bb:cc:dd:ee:ff:11:1e from zone_3 by specifying only those members
        being removed and setting members_remove_only to True
      brocade_zoning_zone:
        credential: "{{ credential }}"
        vfid: -1
        members_remove_only: true
        zones: "{{ zones }}"

    - name: >
        After zoning_zone.yml, remove zone_1 from cfg_1 a by specifying only
        those members being removed and setting members_remove_only to True
        and leave it enabled
      brocade_zoning_cfg:
        credential: "{{ credential }}"
        vfid: -1
        members_remove_only: true
        cfgs: "{{ cfgs }}"
        active_cfg: cfg_1
