# Copyright 2019-2026 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries

- name: Configure zones
  hosts: san_eng_zone_seed_san_a
  gather_facts: false

  vars:
    credential:
      fos_ip_addr: "{{ fos_ip_addr }}"
      fos_user_name: "{{ fos_user_name }}"
      fos_password: "{{ fos_password }}"
      https: "{{ fos_https }}"
    aliases:
      - name: alias_host_1
        members:
          - aa:bb:cc:dd:ee:ff:11:1a
          - aa:bb:cc:dd:ee:ff:11:1b
      - name: alias_target_1
        members:
          - aa:bb:cc:dd:ee:ff:11:1c
      - name: alias_target_2
        members:
          - aa:bb:cc:dd:ee:ff:11:1d
      - name: alias_target_3
        members:
          - aa:bb:cc:dd:ee:ff:11:20
    aliases_to_delete:
      - name: alias_target_2
      - name: alias_target_3
    zones:
      - name: zone_1
        members:
          - alias_host_1
          - alias_target_1
      - name: zone_2
        members:
          - alias_host_1
          - alias_target_2
      - name: zone_3
        members:
          - aa:bb:cc:dd:ee:ff:11:1c
          - aa:bb:cc:dd:ee:ff:11:1d
        principal_members:
          - aa:bb:cc:dd:ee:ff:11:1a
          - aa:bb:cc:dd:ee:ff:11:1b
    zones_to_delete:
      - name: zone_2
      - name: zone_3
    cfgs:
      - name: cfg_1
        members:
          - zone_1
      - name: cfg_2
        members:
          - zone_2
      - name: cfg_3
        members:
          - zone_3
    cfgs_to_delete:
      - name: cfg_2
      - name: cfg_3

  tasks:
    - name: Create aliases
      brocade_zoning_alias:
        credential: "{{ credential }}"
        vfid: -1
        aliases: "{{ aliases }}"
          # aliases_to_delete: "{{ aliases_to_delete }}"

    - name: Create zones
      brocade_zoning_zone:
        credential: "{{ credential }}"
        vfid: -1
        zones: "{{ zones }}"
          # zones_to_delete: "{{ zones_to_delete }}"

    - name: Create cfgs
      brocade_zoning_cfg:
        credential: "{{ credential }}"
        vfid: -1
        cfgs: "{{ cfgs }}"
          # cfgs_to_delete: "{{ cfgs_to_delete }}"
        active_cfg: cfg_1

    - name: Default zoning
      brocade_zoning_default_zone:
        credential: "{{ credential }}"
        vfid: -1
        default_zone_access: allaccess
